packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: false
  msgpackr-extract: false
  sharp: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver
