{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pricecheck.fullname" . }}-env
  labels:
    {{- include "pricecheck.labels" . | nindent 4 }}
    {{- include "pricecheck.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "pricecheck.databaseUrl" . | quote }}
  REDIS_URL: {{ include "pricecheck.redisUrl" . | quote }}
{{- end }}
